config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  put '/photos/:id/update_feature', to: 'photos#update_feature'

  resources :photos, except: [:edit] do 
  	collection do 
  		get :get_data, defaults: { format: 'json' }
  	end
  end

  resources :locations, except: [:new, :create] do 
  	collection do
      post :report
  	end
  end

  root to: "locations#index"

end

app/models/photo.rb
class Photo < GeoLocation
  include Mongoid::Paperclip

  belongs_to :location, inverse_of: :photos, optional: true
  embeds_one :flight_summary, inverse_of: :photo

  accepts_nested_attributes_for :flight_summary

  field :metadata, type: Hash
  field :notes, type: String
  field :features, type: Array
  
  has_mongoid_attached_file :attachment, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/

  before_post_process :extract_metadata
  before_create :set_latlng, :set_geolocation, :assign_location
  after_create :find_features

  def extract_metadata
    tempfile = attachment.queued_for_write[:original].path
    data = Exif::Data.new(tempfile) rescue []
    false if data[:gps][:gps_latitude].blank? || data[:gps][:gps_longitude].blank?
    self.metadata = data.to_h
  end

  def set_latlng
    gps = self.metadata[:gps]
    self.lat = gps[:gps_latitude_ref] == 'N' ? gps[:gps_latitude] : -gps[:gps_latitude]
    self.lng = gps[:gps_longitude_ref] == 'E' ? gps[:gps_longitude] : -gps[:gps_longitude]
    self.alt = gps[:gps_altitude]
  end

  def assign_location
    location = nil
    #NOTE: This is a time consuming operation as the no of location's increase we should either improve the query 
    #using mongodb geo capabilities or move it to bacground job 
    Location.all.each do |l|
      if self.distance_to(l) < 10
        location = l
        break
      end
    end
    if location.blank?
      poi = Location.max(:poi) || 0
      location = Location.create(poi: poi + 1, lat: self.lat, lng: self.lng, alt: self.alt)
    end
    self.location = location
  end

  def get_feature_index(type, count)
    self.features.each_with_index do |feature, idx|
      return idx if feature["type"] == type && feature["count"] == count
    end
    nil
  end

  def find_features
    FindFeaturesJob.perform_later self.id.to_s
  end

  def self.confidence_percent(confidence)
    (confidence * 100 / 5).to_i
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :update_feature]

  def index
    @photos = Photo.all.order_by('metadata.date_time': :desc)
    @locations = Location.all.order_by(poi: :asc)
  end

  def show
  end

  def new
    @photo = Photo.new
    @photo.build_flight_summary
  end

  def edit
  end

  def create
    photos_params[:photos].each do |p|
      @photo = Photo.new(attachment: p[:attachment], flight_summary: FlightSummary.new(flight_params[:flight_summary_attributes]), temperature: photo_params[:temperature])
      @photo.save
    end
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Photos successfully uploaded.' }
      format.json { render :show, status: :created, location: @location }
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        flash.now[:success] = 'Photo was successfully updated.'
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, photo: @photo }
        format.js
      else
        flash.now[:error] = 'Unable to update photo.'
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update_feature
    f_idx = @photo.get_feature_index(feature_params[:type], feature_params[:count].to_i)
    @photo.features[f_idx]["user_assessment"] = feature_params[:user_assessment]
    if @photo.save
      flash.now[:success] = 'Photo was successfully updated.'
    else
      flash.now[:error] = 'Unable to update photo.'
    end
    render template: 'photos/update.js'
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:location_id, :lat, :lng, :alt, :temperature, :notes, metadata: [:date_time, :make, :model, :exposure_time, :iso_speed_ratings, :exposure_bias_value, :focal_length, :max_aperture_value, :metering_mode], flight_summary: [:operator_name, :aircraft_type, :tail_number, :payload, :notes])
    end

    def photos_params
      params.require :photos
      params.permit photos: [:attachment]
    end
    
    def flight_params
      params.require(:photo).permit(:flight_summary_attributes)
    end

    def feature_params
      params.require(:feature).permit(:count, :type, :user_assessment)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6">
    <%= form_with(model: photo, local: true, html: { multipart: true }) do |form| %>
      <% if photo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(photo.errors.count, "error") %> prohibited the images from uploading:</h2>
          <ul>
          <% photo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= form.fields_for :flight_summary do |fs_form| %>
        <div class="form-group">
          <%= fs_form.label :operator_name %>
          <%= fs_form.text_field :operator_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= fs_form.label :aircraft_type %>
          <%= fs_form.text_field :aircraft_type, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= fs_form.label :tail_number %>
          <%= fs_form.text_field :tail_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= fs_form.label :payload %>
          <%= fs_form.text_field :payload, class: "form-control" %>
        </div>
      <% end %>
      <div class="form-group">
        <%= form.label :temperature %>
        <%= form.text_field :temperature, class: "form-control" %>
      </div>
      <%= form.fields_for :flight_summary do |fs_form| %>
        <div class="form-group">
          <%= fs_form.label :notes %>
          <%= fs_form.text_area :notes, cols: 40, rows: 5, class: "form-control" %>
        </div>
      <% end %>
      <div class="form-group">
        <%= file_field_tag 'photos_attachment', multiple: true, name: "photos[][attachment]", class: 'form-control-file btn btn-outline-primary' %>
      </div>
      <div class="form-group">
        <%= form.submit "Upload" , class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/_photo.html.erb
<li><%= image_tag photo.attachment.url(:thumb) %></li>

app/views/photos/edit.html.erb
<h4>Editing Photo</h4>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Picture Database</h4>
<div id="myGrid" style="width:100%; height:500px;"></div>
<br>
<%= link_to 'Upload Photos', new_photo_path %>
<script>
  locationsList = {
    <% @locations.each do |location| %>
    "<%= location.id.to_s %>": "<%= location.name %>",
    <% end %>
  };
</script>

app/views/photos/new.html.erb
<h4>Upload Photos</h4>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', locations_path, class: 'btn btn-outline-secondary' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/photos/update.js.erb
$("#notice").append("<%= raw j render :partial => 'shared/flash_messages' , :locals => { :flash => flash } %>");