config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  put '/photos/:id/update_feature', to: 'photos#update_feature'

  resources :photos, except: [:edit] do 
  	collection do 
  		get :get_data, defaults: { format: 'json' }
  	end
  end

  resources :locations, except: [:new, :create] do 
  	collection do
      post :report
  	end
  end

  root to: "locations#index"

end

app/models/location.rb
class Location < GeoLocation

  field :poi, type: Integer

  field :line_type, type: Integer
  field :last_inspection, type: Date
  field :pole_number, type: String
  field :line_number, type: String
  field :last_repair, type: Date
  field :last_failure, type: Date
  field :last_failure_type, type: String
  field :user_anomaly_detected, type: Boolean

  has_many :photos, inverse_of: :location

  def name
    "POI #{self.poi}"
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.includes(:photos).all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def report
    @locations = Location.find(params[:selected_markers].split(',')) 
    respond_to do |format|
      format.pdf do 
        render :pdf => "generated_report",
               :layout => 'pdf.html.erb'
      end
    end
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @location.update(location_params)
        flash.now[:success] = 'Location was successfully updated.'
        format.html { redirect_to locations_url, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
        format.js
      else
        flash.now[:error] = 'Unable to update location.'
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.fetch(:location, {}).permit(:lat, :lng, :alt, :temperature, :line_type, :last_inspection, :pole_number, :line_number, :line_type, :last_repair, :last_failure, :last_failure_type, :user_anomaly_detected, photos_attributes: [:attachment])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6">
      <%= form_with(model: location) do |form| %>
        <% if location.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
            <ul>
              <% location.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.label :line_type %>
          <%= form.text_field :line_type, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :lat %>
          <%= form.text_field :lat, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :lng %>
          <%= form.text_field :lng, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :alt %>
          <%= form.text_field :alt, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :temperature %>
          <%= form.text_field :temperature, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :last_inspection %>
          <%= form.text_field :last_inspection, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :pole_number %>
          <%= form.text_field :pole_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :line_number %>
          <%= form.text_field :line_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :line_type %>
          <%= form.text_field :line_type, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :last_repair %>
          <%= form.text_field :last_repair, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :last_failure %>
          <%= form.text_field :last_failure, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :last_failure_type %>
          <%= form.text_field :last_failure_type, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.submit "Save" , class: "btn btn-outline-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/_location_details.html.erb
<ul class="list-group">
   <li class="list-group-item"><b><span id="poi_value"><%= l.name %></span></b></li>
   <li class="list-group-item">Line type:&nbsp;<span id="line_type_value"><%= l.line_type %></span> kV</li>
   <li class="list-group-item">Lat:&nbsp;<span id="lat_value"><%= l.lat %></span></li>
   <li class="list-group-item">Long:&nbsp;<span id="long_value"><%= l.lng %></span></li>
   <li class="list-group-item">Alt:&nbsp;<span id="alt_value"><%= l.alt %></span> ft</li>
   <li class="list-group-item">Temperature:&nbsp;<span id="alt_value"><%= l.temperature %></span>&deg;F</li>
   <li class="list-group-item">Last Inspection:&nbsp;<span id="last_inspection_value"><%= l.last_inspection %></span></li>
   <li class="list-group-item">Pole #:&nbsp;<span id="pole_value"><%= l.pole_number %></span></li>
   <li class="list-group-item">Line #:&nbsp;<span id="line_value">9<%= l.line_number %></span></li>
   <li class="list-group-item">Last Repair:&nbsp;<span id="last_repair_value"><%= l.last_repair %></span></li>
   <li class="list-group-item">Last Failure Type:&nbsp;<span id="last_failure_type_value"><%= l.last_failure_type %></span></li>
   <li class="list-group-item">Last Failure Date:&nbsp;<span id="last_failure_date_value"><%= l.last_failure_type %></span></li>
</ul>
<br />
<a id="details_view_link" href="/locations/<%= l.id.to_s %>" class="btn btn-primary btn-block" id="location_detail_link">Detailed View</a>

app/views/locations/_photo_carousel.html.erb
<div id="indexCarousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <% l.photos.all.each_with_index do |photo,index| %>
    <div class="carousel-item <%='active' if index == 1 %>">
      <img class="d-block img-fluid" src="<%= photo.attachment.url(:medium) %>" alt="<%= photo.attachment.original_filename %>">
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#indexCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#indexCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/locations/edit.html.erb
<h1>Editing <%= @location.name %></h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location ,class: "btn btn-primary"  %>	
<%= link_to 'Back', locations_path,class: "btn btn-outline-secondary"  %>

app/views/locations/index.html.erb
<div class="row">
  <div class="col">
    <div class="card" id="details-preview">
      <div class="card-header">
        Detailed Status
      </div>
      <div class="card-block">
        <ul class="list-group">
          <li class="list-group-item"><b><span id="poi_value"></span></b></li>
          <li class="list-group-item">Line type:&nbsp;<span id="line_type_value"></span></li>
          <li class="list-group-item">Lat:&nbsp;<span id="lat_value"></span></li>
          <li class="list-group-item">Long:&nbsp;<span id="long_value"></span></li>
          <li class="list-group-item">Alt:&nbsp;<span id="alt_value"></span></li>
          <li class="list-group-item">Temperature:&nbsp;<span id="alt_value"></span></li>
          <li class="list-group-item">Last Inspection:&nbsp;<span id="last_inspection_value"></span></li>
          <li class="list-group-item">Pole #:&nbsp;<span id="pole_value"></span></li>
          <li class="list-group-item">Line #:&nbsp;<span id="line_value"></span></li>
          <li class="list-group-item">Last Repair:&nbsp;<span id="last_repair_value"></span></li>
          <li class="list-group-item">Last Failure Type:&nbsp;<span id="last_failure_type_value"></span></li>
          <li class="list-group-item">Last Failure Date:&nbsp;<span id="last_failure_date_value"></span></li>
        </ul>
        <br />
        <a id="details_view_link" href="/locations/<%= @locations.first.id.to_s %>" class="btn btn-primary btn-block" id="location_detail_link">Detailed View</a>
      </div>
    </div>
    <br />
    <div class="card">
      <div class="card-header">
        Report Panel
      </div>
      <div class="card-block">
        <%= form_tag report_locations_path(format: :pdf) do-%>
          <%= hidden_field_tag 'selected_markers' %>
          <%= submit_tag "Generate Report", id: "report_submit", class: "btn btn-warning btn-block", disabled: true%>
          <a href="#" class="btn btn-secondary btn-block">Clear All</a>
        <%end%>
      </div>
    </div>
  </div>
  <div class="col-6">
    <div id="map"></div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th># of Photos</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @locations.each do |location| %>
          <tr>
            <td class="col-6"><%= location.name %></td>
            <td class="col-6"><%= location.photos.count %></td>
            <td class="col-2"><%= link_to '<i class="fa fa-map-marker"></i>'.html_safe, location %></td>
            <td class="col-2"><%= link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_location_path(location)  %></td>
            <td class="col-2"><%= link_to '<i class="fa fa-trash-o fa-lg"></i>'.html_safe, location, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% if @locations.present? %>
    <script>
      var first_location_id = "<%= @locations.first.id.to_s %>";
      function initMap() {
        var selecting=false;
        selectedMarkers = [];
            window.onkeydown = function(e) {
            if(e.which == 91 || e.which == 17){
              selecting = true;  
            }
          }
          window.onkeyup = function(e) {
            selecting = false;
          }
        var uluru = {lat: <%= @locations[0].lat %>, lng: <%= @locations[0].lng %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          mapTypeId: google.maps.MapTypeId.HYBRID,
          center: uluru
        });
        <% @locations.each_with_index do |location, i| 
          content = '<ul class="photo_list">'
          for photo in location.photos do
            content += "<li><img src=\"#{photo.attachment.url(:medium)}\"></li>"
          end
          content += '</ul>'
        %>
        infowindow_<%= i %> = new google.maps.InfoWindow({
          content: '<%= raw content %>'
        });

        marker_<%= i %> = new google.maps.Marker({
          position: {lat: <%= location.lat %>, lng: <%= location.lng %>},
          map: map,
          title: "<%= location.name %>",
          animation: google.maps.Animation.DROP,
          id: "<%= location.id %>",
          icon: "<%=location.user_anomaly_detected ? 'https://www.google.com/mapfiles/marker.png' : 'https://www.google.com/mapfiles/marker_yellow.png' %>"
        });
        var markers = [];
        marker_<%= i %>.addListener('click', function(event) {
          
          if (selecting) {
            selectedMarkers.push(marker_<%= i %>.id);  
            marker_<%= i %>.setIcon('https://www.google.com/mapfiles/marker_black.png');
             $('input#selected_markers').val(selectedMarkers.join(","));
             $('input#report_submit').prop('disabled', false);
          }else{
            $('#details_view_link').attr("href", "/locations/"+marker_<%= i %>.id);
            update_location(marker_<%= i %>.id);
          }
        });
        <% end %>
      }
      
      function update_location(id) {
        $.get("/locations/" + id + ".js", function( ) {
      });
    }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBn7yG3_RN21nDgK5gWa-v4Doar92gO7wo&callback=initMap" type="text/javascript"></script>
    <% end %>
  </div>
  <div class="col">
    <div class="card">
      <div class="card-header">
        Legend
      </div>
      <div class="card-block">
        <ul class="list-group">
          <li class="list-group-item"><i class="fa fa-map-marker fa-2x fa-yellow mr-2" aria-hidden="true"></i>Not Validated</li>
          <li class="list-group-item"><i class="fa fa-map-marker fa-2x fa-green mr-2" aria-hidden="true"></i>No Anomalies</li>
          <li class="list-group-item"><i class="fa fa-map-marker fa-2x fa-red mr-2" aria-hidden="true"></i>Anomaly Detected</li>
          <li class="list-group-item"><i class="fa fa-map-marker fa-2x fa-black mr-2" aria-hidden="true"></i>Selected</li>
        </ul>
      </div>
    </div>
    <br />
    <div class="card" id="inspection-preview">
      <div class="card-header">
        Inspection Preview
      </div>
      <div class="card-block">
        <div id="indexCarousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <% Photo.all.limit(3).each_with_index do |photo,index| %>
            <div class="carousel-item <%='active' if index == 1 %>">
              <img class="d-block img-fluid" src="<%= photo.attachment.url(:medium) %>" alt="<%= photo.attachment.original_filename %>">
            </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#indexCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#indexCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<h4>New Location</h4>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/report.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "report" %>
    <%= wicked_pdf_javascript_include_tag "jquery" %>
    <%= wicked_pdf_javascript_include_tag "location" %>
    <script>
      $(document).ready(function() {
      <% @locations.each do |location| %>
        <% location.photos.each do |photo| %>
          <% photo.features.each do |feature| %>
            draw_feature("canvas_<%= photo.id.to_s %>", [<%= feature["coordinates"][0] %>, <%= feature["coordinates"][1] %>, <%= feature["coordinates"][2] %>, <%= feature["coordinates"][3] %>], "<%= feature["color"] %>", .55, "<%= feature["count"] %>");
          <% end %>
        <% end %>
      <% end %>
      });
    </script>
  </head>
  <body>
    <h1 id="report_header">Report</h1>
    <% @locations.each_with_index do |location, l_idx| %>
      <h2 class="<%= l_idx > 0 ? "alwaysbreak" : "" %>"><%= location.name %></h2>
      <% location.photos.each_with_index do |photo, p_idx| %>
      <div class="container<%= p_idx > 0 ? " alwaysbreak" : "" %>">
        <div class="row">
          <div class="col-6">
            <%= wicked_pdf_image_tag photo.attachment.url(:medium) %>
          </div>
          <div class="col-6">
            <%= wicked_pdf_image_tag photo.attachment.url(:medium), width: 300, height: 225 %>
            <canvas id="canvas_<%= photo.id.to_s %>" class="feature-canvas" width="300" height="225"></canvas>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <% if photo.features.count > 0 %>
              <table>
                <tr>
                  <th class="text-left">Feature</th>
                  <th>Confidence</th>
                </tr>
                <% photo.features.each do |feature| %>
                  <tr>
                    <td><%= feature["name"] %></td>
                    <td class="text-right"><%= feature["confidence_percent"] %>%</td>
                  </tr>
                <% end %>
              </table>
            <% end %>
            <p>Notes: <%= photo.notes %></p>
            <p>
              <small class="text-muted">Time updated at: <%= photo.attachment_updated_at %></small>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </body>
<html>

app/views/locations/show.html.erb
<h2><%= @location.name %></h2>
<form id="photo_form">
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          Machine Learning Results
        </div>
        <div class="card-block">
          <ul id="feature-list" class="list-group"></ul>
        </div>
      </div>
      <br />
      <div class="card" id="photo-notes">
        <div class="card-block">
          <input id="user-anomaly" type="checkbox" name="user_anomaly_detected" data-location-id="<%=@location.id%>" value="user_anomaly_detected" <%=@location.user_anomaly_detected ? "checked" : '' %> > User Anomaly detected<br>
        </div>
      </div>
      <br/>
      <div class="card" id="photo-notes">
        <div class="card-header">
          <label for="photo_notes">Notes</label>
        </div>
        <div class="card-block">
          <div class="form-group">
            <input type="hidden" name="photo_id" id="photo_id">
            <textarea name="photo_notes" id="photo_notes" cols="40" rows="5" class="form-control"></textarea>
          </div>
          <div class="form-group" style="margin-bottom:0;">
            <input type="submit" value="Save" class="btn btn-outline-primary">
          </div>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="card" id="inspection-panel">
        <div class="card-header">
          Inspection Preview
        </div>
        <div class="card-block">
          <div id="detailsCarousel" class="carousel slide" data-interval="false" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <% @location.photos.each_with_index do |photo,index| %>
              <div class="carousel-item <%='active' if index == 1 %>">
                <div class="panzoom">
                  <img id="<%= photo.id.to_s %>" src="<%= photo.attachment.url(:original) %>" alt="<%= photo.attachment.original_filename %>" width="600" height="400">
                  <canvas id="canvas_<%= photo.id.to_s %>" class="feature-canvas" width="600" height="400"></canvas>
                </div>
              </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#detailsCarousel" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#detailsCarousel" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="zoom-nav">
            <i class="fa fa-plus zoom-in" aria-hidden="true"></i><i class="fa fa-minus zoom-out" aria-hidden="true"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script>

  var location_id = "<%= @location.id.to_s %>";

</script>

app/views/locations/show.js.erb
$('#inspection-preview .card-block').html("<%=raw escape_javascript render(:partial => 'photo_carousel', :locals => { :l => @location }) %>");
$('#details-preview .card-block').html("<%=raw escape_javascript render(:partial => 'location_details', :locals => { :l => @location }) %>");

app/views/locations/update.js.erb
$("#notice").append("<%= raw j render :partial => 'shared/flash_messages' , :locals => { :flash => flash } %>");